Closes #125 xportr 0.4.0 blog
pharmaverse/blog pull request #126
Opened 2024-02-28 22:14 UTC by sadchla-codes

2024-03-14 12:29 UTC, bms63 commented
Hi @sadchla-codes - how goes the blog post?  We should be moving to CRAN in the next couple of days

2024-03-14 15:46 UTC, sadchla-codes commented
> Hi @sadchla-codes - how goes the blog post? We should be moving to CRAN in the next couple of days

@bms63 It's ready for review!

2024-03-24 17:38 UTC, bms63 reviewed
Whoa... @sadchla-codes this is really good!!  I like the JSON piece at the end.  I have to review more tomorrow.  I think xportr is going to CRAN on Monday or Tuesday

2024-03-24 17:39 UTC, bms63 commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +# About the other kid on the blog, (`JSON`)! Is The Future `XPT` or JSON?
Haha! Amazing!  Can you make a reference to the datasetjson blog post on Atorus' site and the datasetjson package?  

@mstackhouse maybe a follow up blog post on pharamverse is needed about datasetjson??

2024-03-25 07:48 UTC, StefanThoma requested changes
Great post, @sadchla-codes !
I spotted some typos and added some suggestions.

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +In the pharmaceuticals and healthcare industries, it is crucial to maintain a standard structure for data exchange and regulatory submissions, enter `xpt` datasets! `XPT` datasets are binary files th
Why is the second `XPT` all capital?

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +In the pharmaceuticals and healthcare industries, it is crucial to maintain a standard structure for data exchange and regulatory submissions, enter `xpt` datasets! `XPT` datasets are binary files th
I think the last sentence should be rephrased, e.g.

```suggestion
In the pharmaceuticals and healthcare industries, it is crucial to maintain a standard structure for data exchange and regulatory submissions, enter `xpt` datasets! `XPT` datasets are binary files that are typically created by SAS software, they contain structured data, including variables, labels, and metadata. The  [`xportr`](https://atorus-research.github.io/xportr/) package was created specifically to develop `xpt` formatted files in R.
```

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +[`xportr`](https://atorus-research.github.io/xportr/) is tools to build CDISC compliant data sets and check for CDISC compliance. By using  [`xportr`](https://atorus-research.github.io/xportr/), prog
```suggestion
[`xportr`](https://atorus-research.github.io/xportr/) is a tool to build CDISC compliant data sets and check for CDISC compliance. By using  [`xportr`](https://atorus-research.github.io/xportr/), programmers are able to build these CDISC compliant files. 
```

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +[`xportr`](https://atorus-research.github.io/xportr/) has been developed through collaborations between developers from different parts of the industry [click here for a full list](https://atorus-res
```suggestion
[`xportr`](https://atorus-research.github.io/xportr/) has been developed through collaborations between developers from different parts of the industry [click here for a full list](https://atorus-research.github.io/xportr/authors.html). This collaborative effort ensures that [`xportr`](https://atorus-research.github.io/xportr/) meets the diverse needs and requirements of users across various domains. By leveraging insights and expertise from different stakeholders, [`xportr`](https://atorus-research.github.io/xportr/) continues to evolve and improve, maintaining its relevance and effectiveness in the ever-changing landscape of data management and analysis. With its meticulous design flow, users can expect to develop `xpt` files that have been vetted by many checks in the backend and which are CDISC compliant. 
```

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +[`xportr`](https://atorus-research.github.io/xportr/) is currently on version 0.4.0 and you can keep up with all of its improvements by follow the [`Changelog here`](https://atorus-research.github.io
```suggestion
[`xportr`](https://atorus-research.github.io/xportr/) is currently on version 0.4.0 and you can keep up with all of its improvements by following the [`Changelog here`](https://atorus-research.github.io/xportr/news/index.html)
```

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +Have I already mentioned that [`xportr`](https://atorus-research.github.io/xportr/) is an essential R package for generating `xpt` datasets! This package have functions to apply metadata information
```suggestion
Have I already mentioned that [`xportr`](https://atorus-research.github.io/xportr/) is an essential R package for generating `xpt` datasets? This package includes functions to apply metadata information to your CDISC compliant datasets that were created in R, perform checks and provide useful feedbacks. In this blog post, we'll explore some high level  capabilities of [`xportr`](https://atorus-research.github.io/xportr/), and its development.
```

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +Users can use the [`xportr_metadata()`](https://atorus-research.github.io/xportr/reference/xportr_metadata.html) function along with [`xportr_type()`](https://atorus-research.github.io/xportr/referen
```suggestion
Users can use the [`xportr_metadata()`](https://atorus-research.github.io/xportr/reference/xportr_metadata.html) function along with [`xportr_type()`](https://atorus-research.github.io/xportr/reference/xportr_type.html) and [`xportr_order()`](https://atorus-research.github.io/xportr/reference/xportr_order.html) to not only apply metadata attributes to your data but also receive feedback on your data based on your spec – all while also performing valuable checks.
```
What do you mean by "valuable checks"? Could you be more specific?

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +As data continues to play a central role in decision-making and innovation, the future of JavaScript Object Notation (JSON) datasets are worth exploring. JSON datasets offer flexibility, simplicity,
```suggestion
As data continues to play a central role in decision-making and innovation, the future of JavaScript Object Notation (JSON) datasets is worth exploring. JSON datasets offer flexibility, simplicity, and interoperability, making them increasingly popular for data storage and exchange. JSON's lightweight and human-readable format make it suitable for a wide range of applications, including web development, APIs, IoT, and data storage. While `xpt` datasets remain prevalent in certain industries, there's a growing interest in JSON datasets across various domains. Although we will not be exploring JSON datasets, this formatted data type was worth mentioning in this blog.
```

I have heard about JSON being discussed as a standard data format in the industry before. Would you be able to link here some further reading on this?

2024-03-25 07:48 UTC, StefanThoma commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +This blog post highlighted the benefits of using the [`xportr`](https://atorus-research.github.io/xportr/) package, showcased an example of [`xportr`](https://atorus-research.github.io/xportr/) funct
```suggestion
This blog post highlighted the benefits of using the [`xportr`](https://atorus-research.github.io/xportr/) package, showcased an example of [`xportr`](https://atorus-research.github.io/xportr/) function, and discussed the growing interest of JSON datasets in the data landscape. We've also discussed [`xportr`](https://atorus-research.github.io/xportr/)'s development through collaborations between developers from different parts of the industry, highlighting its versatility and relevance in various domains. Which gives me a nice transition to my call to action!! If you haven't used [`xportr`](https://atorus-research.github.io/xportr/) before, then consider this blog as your official invite to test it! Reap the benefit of collaborative efforts across industries and the pharma world. If are already a user of [`xportr`](https://atorus-research.github.io/xportr/) or you are experiencing some issues with a particular functions, then chances are someone else could either be experiencing a similar issue or has an answer to it. So reach out to the team by creating an issue [`here`](https://github.com/atorus-research/xportr/issues).  
```

2024-03-26 19:11 UTC, bms63 commented
@sadchla-codes Could you add a short blurb about what xportr does so it appears on the front page

Please change date and shrink image as well

![image](https://github.com/pharmaverse/blog/assets/10111024/3205a81c-ac4e-45e2-ae2c-ede97f3ecf6f)

Thanks again!!

2024-03-26 19:24 UTC, bms63 commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +  * Variable names must start with a letter (not an underscore), be comprised of only uppercase letters (A-Z), numerals (0-9) and be free of non-ASCII characters, symbols, and underscores.
Could we list out the other functions here.  The xportr_label, xportr_format and xportr_write with the strict checks should get a mention here for sure.

2024-03-26 19:27 UTC, bms63 commented on media/xportr_design_flow.png
Can we increase the size of this image in the post please?

2024-03-26 19:28 UTC, bms63 commented on posts/2024-03-18_xportr_0_4_0/xportr_0_4_0.qmd
> +  * Variable names must start with a letter (not an underscore), be comprised of only uppercase letters (A-Z), numerals (0-9) and be free of non-ASCII characters, symbols, and underscores.
oh and xportr_length

2024-04-02 05:14 UTC, StefanThoma approved these changes
LGTM!!

2024-04-02 14:35 UTC, merged