closes #134 new contributors blog
pharmaverse/blog pull request #135
Opened 2024-03-11 12:01 UTC by rossfarrugia

New blog around tips for new Open source contributors. 

Needs @cpiraux approval before we merge/publish as I shared her story from https://github.com/pharmaverse/pharmaverse/issues/284. Celine - please feel free to add any comments!

2024-03-11 14:21 UTC, manciniedoardo requested changes
Great post! Just some minor things.

2024-03-11 14:21 UTC, manciniedoardo commented on posts/2024-03-11_tips_for__first_.../tips_for__first__time__contributors.qmd
> +(such as git) which could make an initial barrier.
Add explanation for those not familiar with git

```suggestion
(such as [git](https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F)) which could make an initial barrier.
```

2024-03-11 14:21 UTC, manciniedoardo commented on posts/2024-03-11_tips_for__first_.../tips_for__first__time__contributors.qmd
> +than the users themselves. So firstly, please erase from your mind the
```suggestion
than the users themselves? So firstly, please erase from your mind the
```

2024-03-11 14:21 UTC, manciniedoardo commented on posts/2024-03-11_tips_for__first_.../tips_for__first__time__contributors.qmd
> +installing packages using 'install.packages' wouldn't function for
```suggestion
installing packages using `install.packages()` wouldn't function for
```

2024-03-11 14:21 UTC, manciniedoardo commented on posts/2024-03-11_tips_for__first_.../tips_for__first__time__contributors.qmd
> +'devtools::load_all()' to execute the code.*
```suggestion
`devtools::load_all()` to execute the code.*
```

2024-03-11 14:21 UTC, manciniedoardo commented on posts/2024-03-11_tips_for__first_.../tips_for__first__time__contributors.qmd
> +'load_all()', 'document()', 'test()', and 'check()'.*
```suggestion
`load_all()`, `document()`,  `test()`, and `check()`.*
```

2024-03-11 14:55 UTC, manciniedoardo approved these changes

2024-03-11 14:56 UTC, cpiraux approved these changes
Great post! It looks good to me. Thank you, @rossfarrugia, for including my story.

2024-03-11 15:01 UTC, rossfarrugia commented
Thanks Edoardo & Celine! happy for this to be merged anytime. I think the CI checks are failing for other blogs currently from memory, but shout if you want me to fix anything here.

2024-03-11 15:46 UTC, bms63 commented
Hi all,

New spelling and link issues popped up. I have fixed them.  

I only had a few minutes for this today...I love this post and nice to have someting like this on our blog.  With any post I get a little sad when it is just a  "Wall of Text".  Any chance we could break it up with some pretty images???  

Just a couple!!

2024-03-12 11:08 UTC, rossfarrugia commented
> Any chance we could break it up with some pretty images???

I added one for you at the end @bms63 - i tried out adding a few in between the texts but actually felt it had a negative effect reading by breaking up the sections for this one as its so short that i feel it flows nicely as it is. feel free to merge/publish and share some comms if you're OK with it.

I'm presenting at an upcoming PHUSE Webinar Wednesday next month and will reference this blog.

2024-03-12 14:51 UTC, bms63 commented
> > Any chance we could break it up with some pretty images???
> 
> I added one for you at the end @bms63 - i tried out adding a few in between the texts but actually felt it had a negative effect reading by breaking up the sections for this one as its so short that i feel it flows nicely as it is. feel free to merge/publish and share some comms if you're OK with it.
> 
> I'm presenting at an upcoming PHUSE Webinar Wednesday next month and will reference this blog.

Okay makes sense!! :)

2024-03-12 14:58 UTC, merged