teal module clinical blog post #123
pharmaverse/blog pull request #137
Opened 2024-03-25 16:03 UTC by khatril

2024-03-26 19:28 UTC, bms63 commented
@pharmaverse/commswg  Hi all - does anyone have bandwidth to start looking over this blog post?

2024-03-27 08:18 UTC, StefanThoma commented
> @pharmaverse/commswg Hi all - does anyone have bandwidth to start looking over this blog post?

Yes, I can take a look!

2024-03-27 08:29 UTC, StefanThoma requested changes
Great, succinct post. 
Just minor adjustments :)

2024-03-27 08:29 UTC, StefanThoma commented on posts/2024-02-27_tmc_cran/tmc_cran.qmd
> +This significant achievement marks a major milestone for the NEST team in our open-source efforts, that will make a profound impact on the entire open-source community.
```suggestion
This significant achievement marks a major milestone for the NEST team in our open-source efforts that will make a profound impact on the entire open-source community.
```

2024-03-27 08:29 UTC, StefanThoma commented on posts/2024-02-27_tmc_cran/tmc_cran.qmd
> +We would like to give a huge thanks to the hard work and dedication of the many developers (past and present) for making this release possible.
Can you link to the github contributers here?

2024-03-27 08:29 UTC, StefanThoma commented on posts/2024-02-27_tmc_cran/tmc_cran.qmd
> +Designed to enable faster insights generation, the `teal.modules.clinical` package contains a set of standard teal modules to be used with CDISC data in order to generate many of the common analysis
Could you always link to the package when mentioning it?
e.g: 
[{falcon}](https://pharmaverse.github.io/falcon/)

2024-03-27 08:29 UTC, StefanThoma commented on posts/2024-02-27_tmc_cran/tmc_cran.qmd
> +
Could you briefly explain what teal is, in one sentence or so?

2024-04-08 12:41 UTC, khatril commented
Thanks @manciniedoardo @StefanThoma

2024-04-08 12:41 UTC, bms63 commented
@manciniedoardo feel free to publish and announce on slack/Linkedin!!

2024-04-08 12:48 UTC, merged