closes #143 draft blog
pharmaverse/blog pull request #150
Opened 2024-04-15 15:54 UTC by rossfarrugia

Thank you for your Pull Request! We have developed this task checklist to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your blog post.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update), and make sure the corresponding issue is linked in the Development section on the right hand side
- [ ] Run the script from `CICD.R` line by line to first check the spelling in your post and then to make sure your code is compatible with our code-style. Address any incongruences by following the instructions in the file! 
- [ ] Choose (possibly several) `tag(s)` or categories from the current list: `c("Metadata", "SDTM", "ADaM", "TLG", "Shiny", "Community", "Conferences", "Submissions", "Technical")` for your blog post. If you cannot find anything that fits your blog post, add your own tag! We occasionally tidy up all `tags` for consistency.
- [ ] Add a short description for your blog post in the `description` field at the top of the markdown document.
- [ ] Blog post is *short*, *personalized*, *reproducible* and *readable*
- [ ] Add a disclaimer at the top of your post, if appropriate (example: **Disclaimer** 
This blog contains opinions that are of the authors alone and do not necessarily reflect the strategy of their respective organizations.)
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Assign two of us (@bms63, @manciniedoardo, @StefanThoma, @kaz462) as reviewers in the PR.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-04-15 16:07 UTC, rossfarrugia commented
@NavitasLifeSciences i made a draft PR with your blog converted to Quarto, and sent you write access so you can push updates to this blog.

Instead of me reviewing via the PR I just made updates directly to this draft blog for my comments as follows. Of course feel free to change anything back as you own this blog as author. Once you're happy we can tag others from the team to review this.

-	Added ® after any mention of SAS and removed mention of SAS “high cost” as such negative wording would not be suitable to place in a public blog in my opinion
-	Removed the dual programming section as don’t think it added any value for this blog to show that same table can be created in SAS or R
-	Added reference to pharmaverse as otherwise why post this blog on our site
-	I updated some of the wording such as R “usage is currently below par” as I don’t actually think it’s true – some of the blog reads more like a viewpoint from 2-3 years ago compared to the growing momentum we now see in R in our industry
-	Removed “The notable difference between SAS® and R is that SAS® is proprietary software, whereas R is an open-source programming language” as I feel readers would know this
-	Added reference to R consortium R submissions WG
-	I replaced the package examples given with pharmaverse examples as again this is a pharmaverse blog
-	Mentioned R Validation Hub rather than R Foundation for more specificity
-	Added a note on licensing
-	Learning curve of R removed “steep” and “lacks direct support from the company,” as those are not the case in many of the across-industry experiences I’ve seen
-	Added some images to help brighten the blog

2024-04-17 07:57 UTC, rossfarrugia commented
Response from Navitas (Amrita Surendranath) by email:  _We are fine with the changes. Please go ahead with the next steps._

@bms63 @manciniedoardo want to take a look now? The spellcheck fails but I'm pretty sure I had added all those from this blog to wordlist so might be from other blogs, or I'm just missing something obvious...

2024-04-17 11:42 UTC, StefanThoma commented
There is a short script in the R folder that will add all remaining words
to the spellcheck dictionary, for future reference :)

On Wed, Apr 17, 2024 at 9:57 AM Ross Farrugia ***@***.***>
wrote:

> Response from Navitas (Amrita Surendranath) by email: *We are fine with
> the changes. Please go ahead with the next steps.*
>
> @bms63 <https://github.com/bms63> @manciniedoardo
> <https://github.com/manciniedoardo> want to take a look now? The
> spellcheck fails but I'm pretty sure I had added all those from this blog
> to wordlist so might be from other blogs, or I'm just missing something
> obvious...
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pharmaverse/blog/pull/150#issuecomment-2060639620>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJUWWEQECUC3TA3LDEI3TF3Y5YTQHAVCNFSM6AAAAABGHUI7UOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANRQGYZTSNRSGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-17 15:13 UTC, rossfarrugia commented
> There is a short script in the R folder that will add all remaining words to the spellcheck dictionary, for future reference :)

Odd as when I run the sections of `CICD.R` I get: 
`No spelling errors found.   `

So not sure why the check is failing,

2024-04-17 18:44 UTC, StefanThoma commented
> > There is a short script in the R folder that will add all remaining words to the spellcheck dictionary, for future reference :)
> 
> Odd as when I run the sections of `CICD.R` I get: `No spelling errors found. `
> 
> So not sure why the check is failing,

There appears a strange error in our CICD workflow: 
`
Run testthat::test_that(desc = "No Typo", code = testthat::expect_equal(object = spelling::spell_check_files(list.files(pattern = ".*.qmd$", recursive = TRUE), ignore = readr::read_lines("inst/WORDLIST.txt")), expected = spelling::spell_check_files(path = "inst/WORDLIST.txt", ignore = readr::read_lines("inst/WORDLIST.txt"))))
── Failure (???): No Typo ──────────────────────────────────────────────────────
spelling::spell_check_files(...) not equal to spelling::spell_check_files(path = "inst/WORDLIST.txt", ignore = readr::read_lines("inst/WORDLIST.txt")).
Attributes: < Component “row.names”: Numeric: lengths (7, 0) differ >
Component “word”: Lengths ([7](https://github.com/pharmaverse/blog/actions/runs/8692333877/job/23836728476#step:7:8), 0) differ (string compare on first 0)
Component “found”: Length mismatch: comparison on first 0 components
`

@bms63 any ideas?

2024-04-17 18:47 UTC, bms63 commented
Not sure on this error.  Maybe there is a new r-libs spell check we could use?

2024-04-18 10:56 UTC, manciniedoardo requested changes

2024-04-18 10:56 UTC, manciniedoardo commented on posts/2024-04-15_de-_mystifying__.../de-_mystifying__r__programming_in__clinical__trials.qmd
> +these challenges, R is steadily establishing a growing niche within the
```suggestion
these challenges, R is steadily establishing a growing presence within the
```

2024-04-18 10:56 UTC, manciniedoardo commented on posts/2024-04-15_de-_mystifying__.../de-_mystifying__r__programming_in__clinical__trials.qmd
> +for R packages being a common issue.
Can we counterbalance here with another phrase describing the successes that early adopters in R have had? This is an R blog after all

2024-04-18 10:56 UTC, manciniedoardo commented on posts/2024-04-15_de-_mystifying__.../de-_mystifying__r__programming_in__clinical__trials.qmd
> +others. These packages cater to different aspects of clinical trial data
Can we mention the pharmaverse here? Seems like a natural place to do so

2024-04-18 10:56 UTC, manciniedoardo commented on posts/2024-04-15_de-_mystifying__.../de-_mystifying__r__programming_in__clinical__trials.qmd
> +## Author
we generally don't have an author section, please could we remove this?

2024-04-18 10:56 UTC, manciniedoardo commented on posts/2024-04-15_de-_mystifying__.../de-_mystifying__r__programming_in__clinical__trials.qmd
> +Capturing the value of R programming starts with a clear vision for its
can we mention pharmaverse in the conclusion as well please?

2024-04-25 13:56 UTC, manciniedoardo commented
@NavitasLifeSciences thanks for your updates! Blog post is ready now 😄 

@bms63 @StefanThoma I guess we can merge once we find out what's going on with the spellcheck, or we can live dangerously and merge anyway... What do you think?

2024-04-25 13:59 UTC, NavitasLifeSciences commented
Hi Edoardo,

Thank you so much! This is wonderful news.

Best Regards,
Amrita



Internal

From: Edoardo Mancini ***@***.***>
Sent: Thursday, April 25, 2024 7:26 PM
To: pharmaverse/blog ***@***.***>
Cc: Amrita Surendranath ***@***.***>; Mention ***@***.***>
Subject: Re: [pharmaverse/blog] closes #143 Navitas R blog (PR #150)


CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@NavitasLifeSciences<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3135346d-454455534531-ce6e0f089b3378de&q=1&e=6672ab10-5748-4474-bdc2-dafd00a7ff9b&u=https%3A%2F%2Fgithub.com%2FNavitasLifeSciences> thanks for your updates! Blog post is ready now 😄

@bms63<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3135346d-454455534531-a80880b239058224&q=1&e=6672ab10-5748-4474-bdc2-dafd00a7ff9b&u=https%3A%2F%2Fgithub.com%2Fbms63> @StefanThoma<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3135346d-454455534531-09523b88518e8372&q=1&e=6672ab10-5748-4474-bdc2-dafd00a7ff9b&u=https%3A%2F%2Fgithub.com%2FStefanThoma> I guess we can merge once we find out what's going on with the spellcheck, or we can live dangerously and merge anyway... What do you think?

—
Reply to this email directly, view it on GitHub<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3135346d-454455534531-362929321ed70298&q=1&e=6672ab10-5748-4474-bdc2-dafd00a7ff9b&u=https%3A%2F%2Fgithub.com%2Fpharmaverse%2Fblog%2Fpull%2F150%23issuecomment-2077258016>, or unsubscribe<https://protect2.fireeye.com/v1/url?k=31323334-501d2dca-3135346d-454455534531-b76ab935f6b419d4&q=1&e=6672ab10-5748-4474-bdc2-dafd00a7ff9b&u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBHYQGFIHTS6P7G6ZZNDMAQDY7EDQVAVCNFSM6AAAAABGHUI7UOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANZXGI2TQMBRGY>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

*** DISCLAIMER***CONFIDENTIAL AND PRIVILEGED INFORMATION*** The information contained in this communication is intended solely for the use of the individual or entity to whom it is addressed and others authorized to receive it. It may contain confidential or legally privileged information. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and is unlawful. If you have received this communication by error, please notify us immediately by responding to this email and then delete it from your system & backup. NAVITAS is not liable for any improper and/or incomplete transmission of the information contained in this communication or for any delay in its receipt or for any damage caused by malicious code or alteration by any third party. The contents of this email do not necessarily represent the views or policies of NAVITAS.

2024-04-25 14:52 UTC, bms63 commented
If the Spelling is checked locally and is good, then lets just merge it.

2024-05-02 08:20 UTC, merged

2024-05-02 08:20 UTC, rossfarrugia commented
As per Ben and Edoardo's messages i'm merging this one to close it out