Closes #231 blog post data packages relevant to the pharmaverse
pharmaverse/blog pull request #263
Opened 2024-12-14 18:38 UTC by bms63

Thank you for your Pull Request! We have developed this task checklist to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your blog post.

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update), and make sure the corresponding issue is linked in the Development section on the right hand side
- [ ] Ensure your new post folder is of the form `"posts/zzz_DO_NOT_EDIT_<your post title>"`. This is so that the post date can be auto-updated upon the merge into `main`.
- [ ] Run the script from `CICD.R` line by line to first check the spelling in your post and then to make sure your code is compatible with our code-style. Address any incongruences by following the instructions in the file! 
- [ ] Choose (possibly several) `tag(s)` or categories from the current list: ` c("Metadata", "SDTM", "ADaM", "TLG", "Shiny", "Community", "Conferences", "Submissions", "Technical")` for your blog post. If you cannot find anything that fits your blog post, propose a new tag to the maintainers! Note: if you use a tag not from this list, the "Check Post Tags" CICD pipeline will error. We occasionally tidy up all `tags` for consistency.
- [ ] Add a short description for your blog post in the `description` field at the top of the markdown document.
- [ ] Blog post is *short*, *personalized*, *reproducible* and *readable*
- [ ] Add a disclaimer at the top of your post, if appropriate (example: **Disclaimer** 
This blog contains opinions that are of the authors alone and do not necessarily reflect the strategy of their respective organizations.)
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Assign two of us (@bms63, @manciniedoardo, @StefanThoma, @kaz462) as reviewers in the PR.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-12-14 18:41 UTC, bms63 commented
Still a WIP

but do you all know of **any other packages** we could list out here?

I just have: 
* admiral
* random.cdisc.data
* pharmaverseadam
* pharmaversesdtm

I looked at teal.data but that is a just a port of some random.cdisc.data as far as I can tell.

[MedStats](https://github.com/lightbluetitan/meddatasets)https://github.com/[lightbluetitan/meddatasets](https://github.com/lightbluetitan/meddatasets) looked promising but wasn't in the CDISC standard

2024-12-16 13:13 UTC, manciniedoardo commented
> Reference

@khatril have we missed any of the NEST ones?

2024-12-16 15:10 UTC, khatril commented
> > Reference
> 
> @khatril have we missed any of the NEST ones?

Great post! Very useful for our community. 
Rcd is the main one, we use this for the Cardinal project. Some others to think about including are https://github.com/cdisc-org/sdtm-adam-pilot-project (This example CDISC data used in `cards` package). We also have minimal data for examples and tests in the `tern` package.

2024-12-16 18:01 UTC, bms63 commented
> > > Reference
> > 
> > 
> > @khatril have we missed any of the NEST ones?
> 
> Great post! Very useful for our community. Rcd is the main one, we use this for the Cardinal project. Some others to think about including are https://github.com/cdisc-org/sdtm-adam-pilot-project (This example CDISC data used in `cards` package). We also have minimal data for examples and tests in the `tern` package.

thanks @khatril!!

pharamversesdtm is actually sdtm-adam-pilot-project brought up to modern standards.

2025-02-14 13:26 UTC, bms63 commented
I will fix the actions, but @manciniedoardo  and @StefanThoma  this could be reviewed and published today/monday??

2025-02-14 14:08 UTC, StefanThoma requested changes
useful post! 
What is missing for me is a bit of context and guidance: 

1. Which datasets are consistent / compatible across? I.e. could come from the same study?
2. Why are there these different datasets around, how do they differ, and who uses them?
3. Which should I use? 

There is already some of that in here, specifically for the random.cdisc.data, but I'd be curious to know more.

2025-02-14 14:08 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +A set of Study Data Tabulation Model (SDTM) datasets from the Clinical Data Interchange Standards Consortium (CDISC) pilot project used for testing and developing Analysis Data Model (ADaM) datasets
Add link

```suggestion
A set of Study Data Tabulation Model (SDTM) datasets from the Clinical Data Interchange Standards Consortium (CDISC) pilot project used for testing and developing Analysis Data Model (ADaM) datasets inside the pharmaverse family of packages. [A CDISC Pilot](LINK) was conducted somewhere between 2008 and 2010. 
This is that Pilot data but slowly brought up to current CDISC standards.
```

2025-02-14 14:08 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaversesdtm/index.html) and package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
```suggestion
Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaversesdtm/index.html).
The package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
```

2025-02-14 14:08 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaverseadam/index.html) and package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
```suggestion
Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaverseadam/index.html).
The package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
```

2025-02-14 14:08 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +
Could you give some insights as to how these data are different to the ones in admiral / pharmaverseadam?

2025-02-14 14:08 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +They have a wealth of data generated for documentation, demonstrations and testing.  You can find all the datasets and what packages they live in [here](https://insightsengineering.r-universe.dev/dat
Many of them are random.cdisc.data

2025-02-14 15:32 UTC, manciniedoardo commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +A set of Study Data Tabulation Model (SDTM) datasets from the Clinical Data Interchange Standards Consortium (CDISC) pilot project used for testing and developing Analysis Data Model (ADaM) datasets
Not only add link - I would also suggest to add the following:

```suggestion
A set of Study Data Tabulation Model (SDTM) datasets from the Clinical Data Interchange Standards Consortium (CDISC) pilot project used for testing and developing Analysis Data Model (ADaM) datasets inside the pharmaverse family of packages. A CDISC Pilot was conducted somewhere between 2008 and 2010. This is that Pilot data but slowly brought up to current CDISC standards. There are also new datasets in the same style (same `STUDYID`, `USUBJID`s, etc.) added by the {admiral} and the {admiral} extension package teams that provide test data for new domains or specific TAs (ophthalmology, vaccines, etc.).
```

2025-02-14 15:33 UTC, manciniedoardo commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Most common SDTM datasets can be found as well as some specific disease area SDTMs that are not avaiable in the CDISC pilot datasets.
```suggestion
```

This can go if clarifying section is added above.

2025-02-14 15:34 UTC, manciniedoardo commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Limited datasets like `ADSL`, `ADLB` but the template scripts availabe in this package are used to create the ADaMs in {pharmaverseadam}
```suggestion
Limited datasets like `ADSL`, `ADLB` are provided in {admiral}, because the template scripts available in this package are used to create the ADaMs in {pharmaverseadam}.
```

2025-02-14 15:35 UTC, manciniedoardo commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Available on [CRAN](https://cran.r-project.org/web/packages/admiral/index.html) and package is actively maintained on [GitHub](https://github.com/pharmaverse/admiral)
```suggestion
Available on [CRAN](https://cran.r-project.org/web/packages/admiral/index.html). This package is actively maintained on [GitHub](https://github.com/pharmaverse/admiral).
```

2025-02-14 15:39 UTC, manciniedoardo commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +A set of functions to create random Analysis Data Model (ADaM) datasets and cached dataset. ADaM dataset specifications are described by the Clinical Data Interchange Standards Consortium (CDISC) Ana
```suggestion
A set of functions to create random Analysis Data Model (ADaM) datasets and cached datasets. ADaM dataset specifications are described by the Clinical Data Interchange Standards Consortium (CDISC) Analysis Data Model Team. These datasets are used to power the [TLG Catalog](https://insightsengineering.github.io/tlg-catalog/stable/), though the NEST team is actively substituting them for {pharmaverseadam} datasets instead -  see [a recent blog post] about this very effort!
```

2025-02-14 15:39 UTC, manciniedoardo commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Available on [CRAN](https://cran.r-project.org/web/packages/random.cdisc.data/index.html) and package is actively maintained on [GitHub](https://github.com/insightsengineering/random.cdisc.data)
```suggestion
Available on [CRAN](https://cran.r-project.org/web/packages/random.cdisc.data/index.html). The package is actively maintained on [GitHub](https://github.com/insightsengineering/random.cdisc.data) by the NEST team.
```

2025-02-14 15:39 UTC, manciniedoardo commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Available on [CRAN](https://cran.r-project.org/web/packages/random.cdisc.data/index.html) and package is available on [GitHub](https://github.com/SafetyGraphics/safetyData)
```suggestion
Available on [CRAN](https://cran.r-project.org/web/packages/random.cdisc.data/index.html). The package is available on [GitHub](https://github.com/SafetyGraphics/safetyData).
```

2025-02-14 18:42 UTC, bms63 commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +The data presented below is just a start and is presented in order of how I found them. Feel free to get in touch with me for additions or clarifications.
I'm a bit weary of email, but I say find me on slack

2025-02-14 18:49 UTC, bms63 commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +
I've actually never used this package before.  my understanding is it procedurally and randomly generates ADaM data from the ether rather than how admiral does it with pulling in SDTM datasets.  Maybe someone form NEST can chime in here?

2025-02-14 18:50 UTC, bms63 commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +They have a wealth of data generated for documentation, demonstrations and testing.  You can find all the datasets and what packages they live in [here](https://insightsengineering.r-universe.dev/dat
yeah there is some duplication.  Note also that SafetyData is just CDISC Pilot which is pharmaversesdtm

2025-02-14 18:55 UTC, bms63 commented
> useful post! What is missing for me is a bit of context and guidance:
> 
> 1. Which datasets are consistent / compatible across? I.e. could come from the same study?

pharmaversesdtm and SafetyData are ports of CDISC pilot data

> 2. Why are there these different datasets around, how do they differ, and who uses them?

I don't really know that history that well.  I just wanted to gather information on them and have them all in one place for someone who wants to explore CDISC more or wants more data to tests things out (say a new package)

> 3. Which should I use?
> 
> There is already some of that in here, specifically for the random.cdisc.data, but I'd be curious to know more.

I'm reluctant to write an advice section.

Thanks @manciniedoardo and @StefanThoma  for very helpful review (definitely a shoot from the hip blog).  I want to keep this post as simple as possible.  I do plan on updating it with additional sources as they come in - in fact I am hoping this blog shakes the bushes a little as this can not be all the publicly available data out there

2025-02-14 19:33 UTC, bms63 commented
@StefanThoma  and @manciniedoardo  I fixed the GHA action - the AI gods gave me a quick assist.

Ready for final review on Monday

2025-02-17 12:15 UTC, StefanThoma requested changes
Very minor suggestions

2025-02-17 12:15 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +description: "Where is all the data? An intermittent attempt to continuously compile, collate, consolidate, and curate publicly available CDISC data useful for Clinical Reporting in R"
Nice alliteration :)

2025-02-17 12:15 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +A set of functions to create *random* Analysis Data Model (ADaM) datasets and cached datasets. You can find a list of the possible random CDISC datasets generated [here](https://insightsengineering.g
could you link the blog post here?

2025-02-17 12:15 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaverseadam/index.html). Package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
``
```suggestion
Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaverseadam/index.html). This package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
```

2025-02-17 12:15 UTC, StefanThoma commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaversesdtm/index.html). Package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
```suggestion
Available on [CRAN](https://cloud.r-project.org/web/packages/pharmaversesdtm/index.html). This package is actively maintained on [GitHub](https://github.com/pharmaverse/pharmaversesdtm)
```

2025-02-17 13:16 UTC, bms63 commented on posts/zzz_DO_NOT_EDIT_data__packages/data__packages.qmd
> +A set of functions to create *random* Analysis Data Model (ADaM) datasets and cached datasets. You can find a list of the possible random CDISC datasets generated [here](https://insightsengineering.g
updated

2025-02-17 13:16 UTC, bms63 commented
> Very minor suggestions

Thanks @StefanThoma  updated!!

@manciniedoardo publish this post?

2025-02-17 13:48 UTC, manciniedoardo commented
> > Very minor suggestions
> 
> Thanks @StefanThoma updated!!
> 
> @manciniedoardo publish this post?

sure - ill just try update the pot dates workflow before we merge as it's not quite running as expected

2025-02-17 13:59 UTC, merged