Closes #69 code sections
pharmaverse/blog pull request #70
Opened 2023-07-14 11:01 UTC by manciniedoardo

2023-07-17 05:36 UTC, kaz462 requested changes
@manciniedoardo I wasn't aware that the code folding feature in RStudio is called "Code Sections" and it's utilized in the admiral template. Great to know, thanks for sharing this!

2023-07-17 05:36 UTC, kaz462 commented on posts/2023-07-14_code_sections/admiral.png
Would you prefer something other than the admiral hex sticker?
![image](https://github.com/pharmaverse/blog/assets/47867131/46231e19-4bf6-4748-adc4-03da121266e6)

2023-07-17 05:36 UTC, kaz462 commented on posts/2023-07-14_code_sections/code_sections.qmd
> +[Code Sections](https://docs.posit.co/ide/user/ide/guide/code/code-sections.html) are user-generated separators for long R scripts or functions in RStudio. They can be set up by inserting a comment l
Maybe remove "user-generated" or replace it to "can be user-generated"?  
> The Source pane in RStudio supports both automatic and user-defined folding for regions of code.

2023-07-17 05:36 UTC, kaz462 commented on posts/2023-07-14_code_sections/code_sections.qmd
> +Once the user saves this template program and opens it in their the local file system, a 100+ line file instantly becomes more tractable due to the code sections that have been inserted.
```suggestion
Once the user saves this template program and opens it in their local file system, a 100+ line file instantly becomes more tractable due to the code sections that have been inserted.
```

2023-07-17 05:36 UTC, kaz462 commented on posts/2023-07-14_code_sections/code_sections.qmd
> +[Code Sections](https://docs.posit.co/ide/user/ide/guide/code/code-sections.html) are user-generated separators for long R scripts or functions in RStudio. They can be set up by inserting a comment l
```suggestion
[Code Sections](https://docs.posit.co/ide/user/ide/guide/code/code-sections.html) are user-generated separators for long R scripts or functions in RStudio. They can be set up by inserting a comment line followed by four or more dashes in between portions of code, like so:
```

2023-07-17 05:36 UTC, kaz462 commented on posts/2023-07-14_code_sections/code_sections.qmd
> +* Travel in between them using the navigator at the bottom of the code pane, or by pressing ``Shift+Alt+J`.
```suggestion
* Travel in between them using the navigator at the bottom of the code pane, or by pressing `Shift+Alt+J`.
```

2023-07-18 09:22 UTC, manciniedoardo commented on posts/2023-07-14_code_sections/admiral.png
Perhaps we could use the RStudio one? But I didn't see it available. Otherwise I'm happy to go with the admiral one.

2023-07-24 08:31 UTC, StefanThoma commented on posts/2023-07-14_code_sections/admiral.png
We only provide pharmaverse stickers by default. 
Please feel free to add any other image you find fitting for your blog-post. It does not need to be a package sticker either.

2023-07-24 10:02 UTC, manciniedoardo commented on posts/2023-07-14_code_sections/admiral.png
thanks, I replaced with the rstudio hex as this is an rstudio feature.

2023-07-24 11:00 UTC, StefanThoma commented on posts/2023-07-14_code_sections/subsections.png
Additionally, you may want to highlight the unfoldable navigation and overview pane on the right side of the script:
<img width="441" alt="Screenshot 2023-07-24 at 12 59 03" src="https://github.com/pharmaverse/blog/assets/40463122/0e79bf37-1af6-44f4-ac17-0f28f2f09354">

2023-07-24 13:58 UTC, StefanThoma approved these changes

2023-07-24 14:33 UTC, merged