pilot-4-blogpost
pharmaverse/blog pull request #98
Opened 2023-12-19 14:45 UTC by gigikenneth

2024-01-02 10:05 UTC, IsmaelRdz25 commented
Hello folks! Happy new year !

This post is ready for review 👍

2024-01-04 13:59 UTC, bms63 commented
We probably won't publish this one until end of January.  We have an EOY council blog post as well as as a admiral 1.0 that need to go out first.

However, @pharmaverse/commswg is there anyone with some bandwidth to help review in the meantime?

2024-01-10 07:49 UTC, IsmaelRdz25 commented
Hello, end of January sounds okay, I guess this could go well with the submission of the first part of Pilot 4 to FDA by the R Consortium.

2024-01-31 13:36 UTC, IsmaelRdz25 commented
Hello,

Is there any update on the review timeline for this post?
Thanks!

2024-01-31 14:16 UTC, bms63 commented
Hi Ismael!!

Apologies and thank you for the poke!!  I will review today and we can put out on Thursday.

2024-01-31 16:44 UTC, bms63 commented on posts/2023-12-30_containers_webassembly_submission/containers_and_webassembly_submissions.qmd
> +The R Consortium Submission Working Group has now successfully made two pilot submissions to the FDA. All the submissions done by the group are focused on improving practices for R-based clinical tri
can we link to R Consortium page please

2024-01-31 16:45 UTC, bms63 commented on posts/2023-12-30_containers_webassembly_submission/containers_and_webassembly_submissions.qmd
> +date: "2023-12-30"
please update to today's date

2024-01-31 16:46 UTC, bms63 commented on posts/2023-12-30_containers_webassembly_submission/containers_and_webassembly_submissions.qmd
> +
could we say what we mean by a publicly available submission?  like NN has down a full R-based submission, but it isn't available for us to look at (AFAIK) and others have done them (I've been told)

2024-01-31 16:52 UTC, bms63 reviewed
Can you link Appsilon in the beginning of the post?

2024-01-31 16:56 UTC, bms63 commented
omg this is so cool - I mesmerized by the possibilities.  I didn't really catch any grammar or syntax issues just some linking and explanations.

2024-01-31 16:57 UTC, bms63 commented on posts/2023-12-30_containers_webassembly_submission/containers_and_webassembly_submissions.qmd
> +source("appendix.R") insert_appendix( repo_spec = "pharmaverse/blog", name = long_slug ) \`\`\`
can this get wrapped in R code chunk or removed?  We are still unsure what we are doing with this section.

2024-01-31 16:58 UTC, bms63 commented on posts/2023-12-30_containers_webassembly_submission/containers_and_webassembly_submissions.qmd
> +|------------------------------------|------------------------------------|
maybe this could be a small scrollable table?  Just takes up a lot of real estate

2024-01-31 17:00 UTC, bms63 requested changes
Just a few minor updates and then we can get this out!

2024-02-01 09:44 UTC, gigikenneth commented
Hi @bms63 , we've implemented the changes. please could you take a look?

2024-02-01 12:21 UTC, bms63 commented
LGTM!!  Many thanks for putting this together!!  There are some spelling mistakes.  I will fix these in another PR.

2024-02-01 12:21 UTC, merged

2024-02-01 12:26 UTC, gigikenneth commented
Hi @bms63 , thank you so much and happy to help with correcting the spelling errors please.

2024-02-01 13:01 UTC, bms63 commented
Hey all - post is live.  A couple of formatting issues are amiss (the package table and the bolding in middle of post) 

https://pharmaverse.github.io/blog/posts/2024-02-01_containers_webassembly_submission/containers_and_webassembly_submissions.html

Do you mind fixing please? 

I will make a post on slack and LinkedIn soon.

2024-02-01 13:58 UTC, gigikenneth commented
@bms63 
Just maintaining this thread. I've updated the table and text and created another pull request with the changes please. Hopefully it renders properly this time 🙏🏾: https://github.com/pharmaverse/blog/pull/109/commits/77962a6e1b8133e7ba0b5d6398889488edc251e0